FROM ghcr.io/nginxinc/nginx-unprivileged:stable-alpine-slim

EXPOSE 8080

ENV BASE_URL=""
ENV SEERR_BASE_URL=""
ENV JMS_DIAGNOSTICS_ENDPOINT=""
ENV JMS_DIAGNOSTICS_UPSTREAM=""
ENV SEERR_HEADER="null"
ENV FLADDER_WEBPATH="/"

USER root
COPY build/web /usr/share/nginx/html
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN mkdir -p /usr/share/nginx/html/assets/config /etc/nginx/jms && \
    chown -R nginx:nginx /usr/share/nginx/html && \
    chmod +x /docker-entrypoint.sh && \
    chown nginx:nginx /docker-entrypoint.sh && \
    chown -R nginx:nginx /etc/nginx/conf.d /etc/nginx/jms

USER nginx
CMD ["/docker-entrypoint.sh"]
