// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class DirectoryBookmarkPigeonCodecReader: FlutterStandardReader {
}

private class DirectoryBookmarkPigeonCodecWriter: FlutterStandardWriter {
}

private class DirectoryBookmarkPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DirectoryBookmarkPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DirectoryBookmarkPigeonCodecWriter(data: data)
  }
}

class DirectoryBookmarkPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DirectoryBookmarkPigeonCodec(readerWriter: DirectoryBookmarkPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DirectoryBookmark {
  func saveDirectory(key: String, path: String) throws
  func resolveDirectory(key: String) throws -> String?
  func closeDirectory(key: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DirectoryBookmarkSetup {
  static var codec: FlutterStandardMessageCodec { DirectoryBookmarkPigeonCodec.shared }
  /// Sets up an instance of `DirectoryBookmark` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DirectoryBookmark?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let saveDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nl_jknaapen_fladder.directory_bookmark.DirectoryBookmark.saveDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveDirectoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let pathArg = args[1] as! String
        do {
          try api.saveDirectory(key: keyArg, path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveDirectoryChannel.setMessageHandler(nil)
    }
    let resolveDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nl_jknaapen_fladder.directory_bookmark.DirectoryBookmark.resolveDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resolveDirectoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.resolveDirectory(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resolveDirectoryChannel.setMessageHandler(nil)
    }
    let closeDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nl_jknaapen_fladder.directory_bookmark.DirectoryBookmark.closeDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeDirectoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          try api.closeDirectory(key: keyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeDirectoryChannel.setMessageHandler(nil)
    }
  }
}
