cmake_minimum_required(VERSION 3.14)
project(jms_update_tests LANGUAGES CXX)
add_executable(jms_update_test desktop_update_test.cpp)
target_compile_features(jms_update_test PRIVATE cxx_std_17)
target_compile_definitions(jms_update_test PRIVATE FLUTTER_VERSION_BUILD=0 NOMINMAX UNICODE _UNICODE)
target_include_directories(jms_update_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../flutter/ephemeral/cpp_client_wrapper/include" "${CMAKE_CURRENT_SOURCE_DIR}/../../flutter/ephemeral")
target_link_libraries(jms_update_test PRIVATE version wintrust shell32)
